"""Menu items."""

from nautobot.core.apps import NavMenuAddButton, NavMenuGroup, NavMenuItem, NavMenuTab

menu_items = (
    NavMenuTab(
        name="Firewall",
        # weight=150,
        groups=[
            NavMenuGroup(
                name="Address",
                weight=100,
                items=[
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:fqdn_list",
                        name="FQDNs",
                        permissions=["nautobot_plugin_firewall_model.view_fqdn"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:fqdn_add",
                                permissions=["nautobot_plugin_firewall_model.add_fqdn"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:iprange_list",
                        name="IP Ranges",
                        permissions=["nautobot_plugin_firewall_model.view_iprange"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:iprange_add",
                                permissions=["nautobot_plugin_firewall_model.add_iprange"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:addressobject_list",
                        name="Address Objects",
                        permissions=["nautobot_plugin_firewall_model.view_addressobject"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:addressobject_add",
                                permissions=["nautobot_plugin_firewall_model.add_addressobject"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:addressobjectgroup_list",
                        name="Address Object Groups",
                        permissions=["nautobot_plugin_firewall_model.view_addressobjectgroup"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:addressobjectgroup_add",
                                permissions=["nautobot_plugin_firewall_model.add_addressobjectgroup"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:addresspolicyobject_list",
                        name="Address Policy Objects",
                        permissions=["nautobot_plugin_firewall_model.view_addresspolicyobject"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:addresspolicyobject_add",
                                permissions=["nautobot_plugin_firewall_model.add_addresspolicyobject"],
                            ),
                        ],
                    ),
                ],
            ),
            NavMenuGroup(
                name="Service",
                weight=200,
                items=[
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:serviceobject_list",
                        name="Service Objects",
                        permissions=["nautobot_plugin_firewall_model.view_serviceobject"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:serviceobject_add",
                                permissions=["nautobot_plugin_firewall_model.add_serviceobject"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:serviceobjectgroup_list",
                        name="Service Object Groups",
                        permissions=["nautobot_plugin_firewall_model.view_serviceobjectgroup"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:serviceobjectgroup_add",
                                permissions=["nautobot_plugin_firewall_model.add_serviceobjectgroup"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:servicepolicyobject_list",
                        name="Service Policy Objects",
                        permissions=["nautobot_plugin_firewall_model.view_servicepolicyobject"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:servicepolicyobject_add",
                                permissions=["nautobot_plugin_firewall_model.add_servicepolicyobject"],
                            ),
                        ],
                    ),
                ],
            ),
            NavMenuGroup(
                name="User",
                weight=200,
                items=[
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:userobject_list",
                        name="User Objects",
                        permissions=["nautobot_plugin_firewall_model.view_userobject"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:userobject_add",
                                permissions=["nautobot_plugin_firewall_model.add_userobject"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:userobjectgroup_list",
                        name="User Object Groups",
                        permissions=["nautobot_plugin_firewall_model.view_userobjectgroup"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:userobjectgroup_add",
                                permissions=["nautobot_plugin_firewall_model.add_userobjectgroup"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:userpolicyobject_list",
                        name="User Policy Objects",
                        permissions=["nautobot_plugin_firewall_model.view_userpolicyobject"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:userpolicyobject_add",
                                permissions=["nautobot_plugin_firewall_model.add_userpolicyobject"],
                            ),
                        ],
                    ),
                ],
            ),
            NavMenuGroup(
                name="Zone",
                weight=200,
                items=[
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:zone_list",
                        name="Zones",
                        permissions=["nautobot_plugin_firewall_model.view_zone"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:zone_add",
                                permissions=["nautobot_plugin_firewall_model.add_zone"],
                            ),
                        ],
                    ),
                ],
            ),
            NavMenuGroup(
                name="Policy",
                weight=200,
                items=[
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:source_list",
                        name="Sources",
                        permissions=["nautobot_plugin_firewall_model.view_source"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:source_add",
                                permissions=["nautobot_plugin_firewall_model.add_source"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:destination_list",
                        name="Destinations",
                        permissions=["nautobot_plugin_firewall_model.view_destination"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:destination_add",
                                permissions=["nautobot_plugin_firewall_model.add_destination"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:policyrule_list",
                        name="Policy Rules",
                        permissions=["nautobot_plugin_firewall_model.view_policyrule"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:policyrule_add",
                                permissions=["nautobot_plugin_firewall_model.add_policyrule"],
                            ),
                        ],
                    ),
                    NavMenuItem(
                        link="plugins:nautobot_plugin_firewall_model:policy_list",
                        name="Policies",
                        permissions=["nautobot_plugin_firewall_model.view_policy"],
                        buttons=[
                            NavMenuAddButton(
                                link="plugins:nautobot_plugin_firewall_model:policy_add",
                                permissions=["nautobot_plugin_firewall_model.add_policy"],
                            ),
                        ],
                    ),
                ],
            ),
        ],
    ),
)
