# Generated by Django 3.1.13 on 2021-09-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0004_fixup_p2p_broadcast"),
        ("nautobot_firewall_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fqdn",
            name="ip_addresses",
            field=models.ManyToManyField(blank=True, null=True, to="ipam.IPAddress"),
        ),
    ]
