# Generated by Django 3.1.13 on 2021-12-02 02:14

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0005_device_local_context_schema"),
        ("nautobot_firewall_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("weight", models.PositiveSmallIntegerField(default=1000)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["weight", "name"],
            },
        ),
        migrations.AddField(
            model_name="policy",
            name="devices",
            field=models.ManyToManyField(blank=True, to="dcim.Device"),
        ),
        migrations.AddField(
            model_name="addressobject",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="addressobjectgroup",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="addresspolicyobject",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="fqdn",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="iprange",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="serviceobject",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="serviceobjectgroup",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="servicepolicyobject",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="sourcedestination",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="userobject",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="userobjectgroup",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="userpolicyobject",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_firewall_models.role"
            ),
        ),
    ]
