# Generated by Django 3.2.13 on 2022-04-23 23:14

from django.db import migrations
import yaml


def create_status(apps, schedma_editor):
    """Initial subset of statuses."""

    statuses = ["active", "staged", "decommissioned"]
    ContentType = apps.get_model("contenttypes.ContentType")
    for i in statuses:
        status = apps.get_model("extras.Status").objects.get(slug=i)
        for model in apps.app_configs["nautobot_firewall_models"].get_models():
            ct = ContentType.objects.get_for_model(model)
            status.content_types.add(ct)


def create_default_objects(apps, schema_editor):
    """Initial subset of commonly used objects."""
    apps.get_model("nautobot_firewall_models.AddressPolicyObject").objects.create(
        name="ANY", description="Used to signify ANY AddressObject."
    )
    apps.get_model("nautobot_firewall_models.UserPolicyObject").objects.create(
        name="ANY", description="Used to signify ANY UserObject."
    )
    apps.get_model("nautobot_firewall_models.ServicePolicyObject").objects.create(
        name="ANY", description="Used to signify ANY ServiceObject."
    )
    with open("nautobot_firewall_models/migrations/services.yml", "r") as f:
        services = yaml.safe_load(f)

    for i in services:
        apps.get_model("nautobot_firewall_models.ServiceObject").objects.create(**i)


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0033_add__optimized_indexing"),
        ("nautobot_firewall_models", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code=create_status),
        migrations.RunPython(code=create_default_objects),
    ]
