# Generated by Django 3.1.13 on 2021-12-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0005_device_local_context_schema"),
        ("nautobot_firewall_models", "0002_policy_devices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="devices",
            field=models.ManyToManyField(blank=True, to="dcim.Device"),
        ),
    ]
