# Generated by Django 3.2.13 on 2022-06-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_firewall_models", "0003_default_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyrule",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="serviceobject",
            unique_together=set(),
        ),
    ]
