# Generated by Django 3.2.13 on 2022-04-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_firewall_models", "0003_status_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyrule",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_rules",
                to="nautobot_firewall_models.destination",
            ),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_rules",
                to="nautobot_firewall_models.source",
            ),
        ),
    ]
