# Generated by Django 3.2.13 on 2022-05-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_firewall_models", "0004_auto_20220426_2132"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="address",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="status",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="zone",
        ),
        migrations.RemoveField(
            model_name="servicepolicyobject",
            name="service_object_groups",
        ),
        migrations.RemoveField(
            model_name="servicepolicyobject",
            name="service_objects",
        ),
        migrations.RemoveField(
            model_name="servicepolicyobject",
            name="status",
        ),
        migrations.RemoveField(
            model_name="servicepolicyobject",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="source",
            name="address",
        ),
        migrations.RemoveField(
            model_name="source",
            name="status",
        ),
        migrations.RemoveField(
            model_name="source",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="source",
            name="user",
        ),
        migrations.RemoveField(
            model_name="source",
            name="zone",
        ),
        migrations.RemoveField(
            model_name="userpolicyobject",
            name="status",
        ),
        migrations.RemoveField(
            model_name="userpolicyobject",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="userpolicyobject",
            name="user_object_groups",
        ),
        migrations.RemoveField(
            model_name="userpolicyobject",
            name="user_objects",
        ),
        migrations.RemoveField(
            model_name="policyrule",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="policyrule",
            name="source",
        ),
        migrations.AddField(
            model_name="policyrule",
            name="destination_address",
            field=models.ManyToManyField(
                null=True, related_name="destination_policy_rules", to="nautobot_firewall_models.AddressObject"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="destination_address_group",
            field=models.ManyToManyField(
                null=True, related_name="destination_policy_rules", to="nautobot_firewall_models.AddressObjectGroup"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="destination_zone",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destination_policy_rules",
                to="nautobot_firewall_models.zone",
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="request_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="service_group",
            field=models.ManyToManyField(
                null=True, related_name="policy_rules", to="nautobot_firewall_models.ServiceObjectGroup"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="source_address",
            field=models.ManyToManyField(
                null=True, related_name="source_policy_rules", to="nautobot_firewall_models.AddressObject"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="source_address_group",
            field=models.ManyToManyField(
                null=True, related_name="source_policy_rules", to="nautobot_firewall_models.AddressObjectGroup"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="source_user",
            field=models.ManyToManyField(
                null=True, related_name="policy_rules", to="nautobot_firewall_models.UserObject"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="source_user_group",
            field=models.ManyToManyField(
                null=True, related_name="policy_rules", to="nautobot_firewall_models.UserObjectGroup"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="source_zone",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_policy_rules",
                to="nautobot_firewall_models.zone",
            ),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name="policyrule",
            name="service",
        ),
        migrations.AddField(
            model_name="policyrule",
            name="service",
            field=models.ManyToManyField(
                null=True, related_name="policy_rules", to="nautobot_firewall_models.ServiceObject"
            ),
        ),
        migrations.DeleteModel(
            name="AddressPolicyObject",
        ),
        migrations.DeleteModel(
            name="Destination",
        ),
        migrations.DeleteModel(
            name="ServicePolicyObject",
        ),
        migrations.DeleteModel(
            name="Source",
        ),
        migrations.DeleteModel(
            name="UserPolicyObject",
        ),
    ]
