# Generated by Django 3.2.13 on 2022-05-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_firewall_models", "0004_on_delete_cascade_on_northbound_obj"),
    ]

    operations = [
        migrations.RenameField(
            model_name="policy",
            old_name="devices",
            new_name="assigned_devices",
        ),
        migrations.RenameField(
            model_name="policy",
            old_name="dynamic_groups",
            new_name="assigned_dynamic_groups",
        ),
        migrations.AlterField(
            model_name="addressobjectgroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="fqdn",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="policy",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="slug",
            field=models.SlugField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceobjectgroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userobject",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userobject",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userobjectgroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
