# Generated by Django 3.2.15 on 2022-08-27 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_firewall_models", "0007_renaming_part2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policyrule",
            options={"ordering": ["index"], "verbose_name_plural": "Policy Rules"},
        ),
        migrations.AlterModelOptions(
            name="policyrulem2m",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="policyrulem2m",
            name="unique_with_index",
        ),
        migrations.RemoveConstraint(
            model_name="policyrulem2m",
            name="unique_without_index",
        ),
        migrations.RemoveField(
            model_name="policyrulem2m",
            name="index",
        ),
    ]
