# Generated by Django 3.2.15 on 2022-09-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_firewall_models", "0008_renaming_part3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policyrulem2m",
            options={"ordering": ["rule__index"]},
        ),
    ]
