# Generated by Django 3.2.20 on 2023-09-04 19:11

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.statuses
import nautobot_firewall_models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0098_rename_data_jobresult_result"),
        ("nautobot_firewall_models", "0014_custom_status_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressobject",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="addressobject",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_addressobject_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="addressobject",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="addressobjectgroup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="addressobjectgroup",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_addressobjectgroup_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="addressobjectgroup",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_applicationobject_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="applicationobjectgroup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationobjectgroup",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_applicationobjectgroup_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="applicationobjectgroup",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="capircapolicy",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="capircapolicy",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="fqdn",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="fqdn",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_fqdn_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="fqdn",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="iprange",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="iprange",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_iprange_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="iprange",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="natpolicy",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="natpolicy",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_natpolicy_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="natpolicy",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_natpolicyrule_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_policy_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_policyrule_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_serviceobject_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="serviceobjectgroup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceobjectgroup",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_serviceobjectgroup_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="serviceobjectgroup",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="userobject",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="userobject",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_userobject_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="userobject",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="userobjectgroup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="userobjectgroup",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_userobjectgroup_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="userobjectgroup",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                default=nautobot_firewall_models.utils.get_default_status,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_firewall_models_zone_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterUniqueTogether(
            name="policyrule",
            unique_together={("name", "action", "index")},
        ),
    ]
