# Generated by Django 3.2.15 on 2023-05-03 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0014_location_status_data_migration"),
        ("nautobot_firewall_models", "0014_custom_status_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capircapolicy",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capirca_policy",
                to="dcim.device",
            ),
        ),
    ]
