# Generated by Django 3.2.20 on 2023-09-04 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_firewall_models", "0015_nautobot_v2_migrations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policyrule",
            options={"ordering": ["index", "name"], "verbose_name_plural": "Policy Rules"},
        ),
    ]
