# Generated by Django 3.2.21 on 2023-09-28 17:07

from django.db import migrations, models

import nautobot_firewall_models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_firewall_models", "0019_resolve_issues_through_tables_part3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationobject",
            name="category",
            field=models.CharField(blank=True, default="", max_length=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="default_ip_protocol",
            field=models.CharField(blank=True, default="", max_length=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="default_type",
            field=models.CharField(blank=True, default="", max_length=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="technology",
            field=models.CharField(blank=True, default="", max_length=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationobjectgroup",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="capircapolicy",
            name="cfg",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="capircapolicy",
            name="net",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="capircapolicy",
            name="pol",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="capircapolicy",
            name="svc",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="request_id",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="request_id",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="port",
            field=models.CharField(
                blank=True, default="", max_length=20, validators=[nautobot_firewall_models.validators.validate_port]
            ),
            preserve_default=False,
        ),
    ]
