# Generated by Django 3.2.21 on 2024-04-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_firewall_models', '0020_field_cleanups'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressobjectgroup',
            name='address_object_groups',
            field=models.ManyToManyField(blank=True, related_name='_nautobot_firewall_models_addressobjectgroup_address_object_groups_+', to='nautobot_firewall_models.AddressObjectGroup'),
        ),
    ]
