# Generated by Django 3.2.21 on 2024-03-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_firewall_models", "0020_field_cleanups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="natpolicyrule",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
