# Generated by Django 3.2.21 on 2024-04-06 00:53

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0098_rename_data_jobresult_result"),
        ("dcim", "0049_remove_slugs_and_change_device_primary_ip_fields"),
        ("nautobot_firewall_models", "0020_field_cleanups"),
    ]

    operations = [
        migrations.RenameModel("CapircaPolicy", "AerleonPolicy"),
        migrations.AlterModelOptions(
            name="aerleonpolicy",
            options={"ordering": ["device"], "verbose_name_plural": "Aerleon Policies"},
        ),
        migrations.AlterField(
            model_name="aerleonpolicy",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aerleon_policy",
                to="dcim.device",
            ),
        ),
    ]
