# Generated by Django 4.2.16 on 2024-10-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0062_module_data_migration"),
        ("extras", "0114_computedfield_grouping"),
        ("nautobot_firewall_models", "0021_alter_addressobject_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="natpolicy",
            name="assigned_devices",
            field=models.ManyToManyField(
                blank=True,
                related_name="nat_policies",
                through="nautobot_firewall_models.NATPolicyDeviceM2M",
                to="dcim.device",
            ),
        ),
        migrations.AlterField(
            model_name="natpolicy",
            name="assigned_dynamic_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="nat_policies",
                through="nautobot_firewall_models.NATPolicyDynamicGroupM2M",
                to="extras.dynamicgroup",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="assigned_devices",
            field=models.ManyToManyField(
                blank=True,
                related_name="firewall_policies",
                through="nautobot_firewall_models.PolicyDeviceM2M",
                to="dcim.device",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="assigned_dynamic_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="firewall_policies",
                through="nautobot_firewall_models.PolicyDynamicGroupM2M",
                to="extras.dynamicgroup",
            ),
        ),
    ]
