# Generated by Django 4.2.19 on 2025-09-19 15:29

from django.db import migrations, models

import nautobot_firewall_models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_firewall_models", "0022_fix_policy_natpolicy_m2ms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressobject",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="addressobject",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="addressobjectgroup",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="addressobjectgroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="default_ip_protocol",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="default_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="subcategory",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationobject",
            name="technology",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationobjectgroup",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="applicationobjectgroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="fqdn",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="fqdn",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="iprange",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="natpolicy",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="natpolicy",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="request_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="policy",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="policy",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="action",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="request_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="ip_protocol",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="serviceobject",
            name="port",
            field=models.CharField(
                blank=True, max_length=255, validators=[nautobot_firewall_models.validators.validate_port]
            ),
        ),
        migrations.AlterField(
            model_name="serviceobjectgroup",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="serviceobjectgroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userobject",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userobject",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userobjectgroup",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="userobjectgroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
