# Generated by Django 4.2.22 on 2025-06-04 14:34


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0114_computedfield_grouping"),
        ("dcim", "0062_module_data_migration"),
        ("nautobot_firewall_models", "0022_fix_policy_natpolicy_m2ms"),
    ]

    operations = [
        migrations.RenameModel("CapircaPolicy", "AerleonPolicy"),
        migrations.AlterModelOptions(
            name="aerleonpolicy",
            options={"ordering": ["device"], "verbose_name_plural": "Aerleon Policies"},
        ),
        migrations.AlterField(
            model_name="aerleonpolicy",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aerleon_policy",
                to="dcim.device",
            ),
        ),
    ]
