# Generated by Django 4.2.24 on 2025-10-11 19:38

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0074_alter_rack_u_height"),
        ("extras", "0125_jobresult_date_started"),
        ("nautobot_firewall_models", "0023_alter_addressobject_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("firewall_config_type", models.CharField(default="aerleon", max_length=50)),
                ("pol", models.TextField(blank=True)),
                ("net", models.TextField(blank=True)),
                ("svc", models.TextField(blank=True)),
                ("cfg", models.TextField(blank=True)),
                (
                    "device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firewall_config",
                        to="dcim.device",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name_plural": "Firewall Configs",
                "ordering": ["device"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
