# Generated by Django 4.2.22 on 2025-07-09 17:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


def forward_func_copy_device_ids_to_object_ids(apps, *_):
    AerleonPolicy = apps.get_model("nautobot_firewall_models", "AerleonPolicy")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Device = apps.get_model("dcim", "Device")
    device_type = ContentType.objects.get_for_model(Device)
    for ap in AerleonPolicy.objects.all():
        ap.content_type = device_type
        ap.object_id = ap.device_id
        ap.save()


def reverse_func_copy_object_ids_to_device_ids(apps, *_):
    AerleonPolicy = apps.get_model("nautobot_firewall_models", "AerleonPolicy")
    Device = apps.get_model("dcim", "Device")
    ContentType = apps.get_model("contenttypes", "ContentType")
    device_ct = ContentType.objects.get_for_model(Device)
    for ap in AerleonPolicy.objects.all():
        if ap.content_type == device_ct:
            ap.device_id = ap.object_id
            ap.save()
        else:
            # dropping AerleonPolicy, as previous code is not backwards compatible
            # with types other than device
            ap.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('virtualization', '0026_change_virtualmachine_primary_ip_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('nautobot_firewall_models', '0023_aerleonpolicy_rename_capircapolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyVirtualMachineM2M",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nautobot_firewall_models.policy"
                    ),
                ),
                (
                    "virtual_machine",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="virtualization.virtualmachine"),
                ),
            ],
            options={
                "ordering": ["weight"],
                "unique_together": {("policy", "virtual_machine")},
            },
        ),
        migrations.AddField(
            model_name="policy",
            name="assigned_virtual_machines",
            field=models.ManyToManyField(
                blank=True,
                related_name="firewall_policies",
                through="nautobot_firewall_models.PolicyVirtualMachineM2M",
                to="virtualization.virtualmachine",
            ),
        ),
        migrations.AlterModelOptions(
            name="aerleonpolicy",
            options={"verbose_name_plural": "Aerleon Policies"},
        ),
        migrations.AddField(
            model_name="aerleonpolicy",
            name="content_type",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aerleonpolicy",
            name="object_id",
            field=models.UUIDField(default="3806fd77-9df1-4b19-bfab-867ec6b5b74a"),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="aerleonpolicy",
            index=models.Index(fields=["content_type", "object_id"], name="nautobot_fi_content_1df538_idx"),
        ),
        migrations.RunPython(
            code=forward_func_copy_device_ids_to_object_ids,
            reverse_code=reverse_func_copy_object_ids_to_device_ids,
        ),
        migrations.RemoveField(
            model_name="aerleonpolicy",
            name="device",
        ),
        migrations.CreateModel(
            name="NATPolicyVirtualMachineM2M",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                (
                    "nat_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nautobot_firewall_models.natpolicy"
                    ),
                ),
                (
                    "virtual_machine",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="virtualization.virtualmachine"),
                ),
            ],
            options={
                "ordering": ["weight"],
                "unique_together": {("nat_policy", "virtual_machine")},
            },
        ),
        migrations.AddField(
            model_name="natpolicy",
            name="assigned_virtual_machines",
            field=models.ManyToManyField(
                blank=True,
                related_name="nat_policies",
                through="nautobot_firewall_models.NATPolicyVirtualMachineM2M",
                to="virtualization.virtualmachine",
            ),
        ),
        migrations.AlterModelOptions(
            name="aerleonpolicy",
            options={"ordering": ["pk"], "verbose_name_plural": "Aerleon Policies"},
        ),
    ]
