# Generated by Django 4.2.22 on 2025-06-27 16:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtualization", "0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more"),
        ("nautobot_firewall_models", "0023_aerleonpolicy_rename_capircapolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyVirtualMachineM2M",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nautobot_firewall_models.policy"
                    ),
                ),
                (
                    "virtual_machine",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="virtualization.virtualmachine"),
                ),
            ],
            options={
                "ordering": ["weight"],
                "unique_together": {("policy", "virtual_machine")},
            },
        ),
        migrations.AddField(
            model_name="policy",
            name="assigned_virtual_machines",
            field=models.ManyToManyField(
                blank=True,
                related_name="firewall_policies",
                through="nautobot_firewall_models.PolicyVirtualMachineM2M",
                to="virtualization.virtualmachine",
            ),
        ),
    ]
