# Generated by Django 4.2.22 on 2025-06-04 14:34


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0049_remove_slugs_and_change_device_primary_ip_fields"),
        ("extras", "0098_rename_data_jobresult_result"),
        ("nautobot_firewall_models", "0023_alter_addressobject_description_and_more"),
    ]

    operations = [
        migrations.RenameModel("CapircaPolicy", "AerleonPolicy"),
        migrations.AlterModelOptions(
            name="aerleonpolicy",
            options={"ordering": ["device"], "verbose_name_plural": "Aerleon Policies"},
        ),
        migrations.AlterField(
            model_name="aerleonpolicy",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aerleon_policy",
                to="dcim.device",
            ),
        ),
    ]
