# Generated by Django 4.2.23 on 2025-07-02 14:49

import django.db.models.deletion
from django.db import migrations, models


def forward_func_copy_device_ids_to_object_ids(apps, *_):
    AerleonPolicy = apps.get_model("nautobot_firewall_models", "AerleonPolicy")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Device = apps.get_model("dcim", "Device")
    device_type = ContentType.objects.get_for_model(Device)
    for ap in AerleonPolicy.objects.all():
        ap.content_type = device_type
        ap.object_id = ap.device_id
        ap.save()


def reverse_func_copy_object_ids_to_device_ids(apps, *_):
    AerleonPolicy = apps.get_model("nautobot_firewall_models", "AerleonPolicy")
    for ap in AerleonPolicy.objects.all():
        ap.device_id = ap.object_id
        ap.save()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("nautobot_firewall_models", "0024_policyvirtualmachinem2m_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aerleonpolicy",
            options={"verbose_name_plural": "Aerleon Policies"},
        ),
        migrations.AddField(
            model_name="aerleonpolicy",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                default=1,  # placeholder
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aerleonpolicy",
            name="object_id",
            field=models.UUIDField(default="3806fd77-9df1-4b19-bfab-867ec6b5b74a"),  # placeholder
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="aerleonpolicy",
            index=models.Index(fields=["content_type", "object_id"], name="nautobot_fi_content_1df538_idx"),
        ),
        migrations.RunPython(forward_func_copy_device_ids_to_object_ids, reverse_func_copy_object_ids_to_device_ids),
        migrations.RemoveField(
            model_name="aerleonpolicy",
            name="device",
        ),
        migrations.AlterModelOptions(
            name="aerleonpolicy",
            options={"ordering": ["object_id"], "verbose_name_plural": "Aerleon Policies"},
        ),
    ]
