# Generated by Django 4.2.22 on 2025-07-09 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_firewall_models", "0026_natpolicyvirtualmachinem2m_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aerleonpolicy",
            options={"ordering": ["pk"], "verbose_name_plural": "Aerleon Policies"},
        ),
    ]
