# Generated by Django 3.1.13 on 2021-09-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_plugin_firewall_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyrule",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
