---
- name: FTP
  port: "20-21"
  ip_protocol: TCP
- name: SSH
  port: "22"
  ip_protocol: TCP
- name: TELNET
  port: "23"
  ip_protocol: TCP
- name: SMTP
  port: "25"
  ip_protocol: TCP
- name: HTTP
  port: "80"
  ip_protocol: TCP
- name: HTTP-DEV
  port: "8080"
  ip_protocol: TCP
- name: HTTPS
  port: "443"
  ip_protocol: TCP
- name: HTTPS-DEV
  port: "4443"
  ip_protocol: TCP
- name: NTP
  port: "123"
  ip_protocol: UDP
- name: ICMP
  ip_protocol: ICMP
