---
name: "Check Migrations"
# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      db-backend:
        description: "Database Backend"
        required: true
        type: "string"
      nautobot-version:
        description: "Nautobot Version"
        required: true
        type: "string"
      python-version:
        description: "Python Version"
        required: true
        type: "string"
      tag-prefix:
        description: "Docker Image Tag Prefix"
        required: true
        type: "string"
      use-cache:
        description: "Whether to use GitHub Actions cache"
        required: true
        type: "boolean"
jobs:
  check-migrations:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Configure Compose"
        id: "config"
        uses: "./.github/actions/config-compose"
        with:
          db-backend: "${{ inputs.db-backend }}"
          nautobot-version: "${{ inputs.nautobot-version }}"
          python-version: "${{ inputs.python-version }}"
          tag-prefix: "${{ inputs.tag-prefix }}"
          use-cache: "${{ inputs.use-cache }}"
      - name: "Check Migrations"
        env:
          COMPOSE_ANSI: "0"
          COMPOSE_FILE: "${{ steps.config.outputs.compose-file }}"
          NAUTOBOT_VER: "${{ inputs.nautobot-version }}"
          PYTHON_VER: "${{ inputs.python-version }}"
        run: |
          cd development
          docker compose run \
            --rm \
            --entrypoint='' \
            -- \
            nautobot \
            invoke check-migrations
