---
name: "Run Linters"
# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      nautobot-version:
        description: "Nautobot Version"
        required: true
        type: "string"
      python-version:
        description: "Python Version"
        required: true
        type: "string"
      tag-prefix:
        description: "Docker Image Tag Prefix"
        required: true
        type: "string"
      use-cache:
        description: "Whether to use GitHub Actions cache"
        required: true
        type: "boolean"
jobs:
  linters:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Configure Compose"
        id: "config"
        uses: "./.github/actions/config-compose"
        with:
          nautobot-version: "${{ inputs.nautobot-version }}"
          python-version: "${{ inputs.python-version }}"
          tag-prefix: "${{ inputs.tag-prefix }}"
          use-cache: "${{ inputs.use-cache }}"
      - name: "Run Linters"
        uses: "./.github/actions/run-linters"
        with:
          compose-file: "${{ steps.config.outputs.compose-file }}"
          nautobot-version: "${{ inputs.nautobot-version }}"
          python-version: "${{ inputs.python-version }}"
